const SETLOGINSTATUS = 'SETLOGINSTATUS'
const SETUSERINFO = 'SETUSERINFO'
const SETHEADERTEXT = 'SETHEADERTEXT'
const SETHEADERRIGHTTEXT = 'SETHEADERRIGHTTEXT'
const SETIDCARDIMG = 'SETIDCARDIMG'
const SETAPTITUDESIMG = 'SETAPTITUDESIMG'
const SETCITY = 'SETCITY'
const CURRENTCITY = 'CURRENTCITY'
const SETORDERCONDITION = 'SETORDERCONDITION'
const SETALLREADY = 'SETALLREADY'
const SETNEWSTYPE = 'SETNEWSTYPE'
const SETJDBTOKEN = 'SETJDBTOKEN'
const SETPOSITIONY = 'SETPOSITIONY'
const SENDORDERSCITY = 'SENDORDERSCITY'
export {
  SETLOGINSTATUS,
  SETUSERINFO,
  SETHEADERTEXT,
  SETHEADERRIGHTTEXT,
  SETIDCARDIMG,
  SETAPTITUDESIMG,
  SETCITY, CURRENTCITY,
  SETORDERCONDITION,
  SETALLREADY,
  SETNEWSTYPE,
  SETJDBTOKEN,
  SETPOSITIONY,
  SENDORDERSCITY
}
